### PR TITLE
Various fixes and tweaks for 1.12.2

### LINKED ISSUE #1200: Untextured particles
These blocks have untextured particles when running/jumping on them:
- all three chests
- Escritoire
- Analyzer
- all three engines
- Still
- Bottler
- Carpenter
- Squeezer
- Moistener
- Fermenter
- Centrifuge
- Rainmaker

Using:
Forge 12.16.1.1907
Forestry 1.9-5.0.0.31

### LINKED ISSUE #2574: erroneous nbt format of letter
nbt in forestry.core.inventory.ItemInventory.setUID and forestry.core.inventory.ItemInventory.isSameItemInventory is Integer, bug in forestry.mail.Letter.<init> is String

private void setUID(NBTTagCompound nbt) {
	if (!nbt.hasKey(KEY_UID)) {
		nbt.**setInteger**(KEY_UID, rand.nextInt());
	}
}

public Letter(NBTTagCompound nbttagcompound) {
	this.isProcessed = nbttagcompound.getBoolean("PRC");
	this.sender = new MailAddress(nbttagcompound.getCompoundTag("SDR"));
	this.recipient = new MailAddress(nbttagcompound.getCompoundTag("RC"));

	this.text = nbttagcompound.getString("TXT");
	this.uid = nbttagcompound.**getString**("UID");
	this.inventory.readFromNBT(nbttagcompound);
}

### LINKED ISSUE #2579: Carpenter oredict recipe dupe bug
Steps to reproduce:

1. Put any OreDict'ed recipe. eg:
image
2. Put in Inventory only part of required OreDict'ed ingredients 
3. 
image

Forestry version: 1.12.2-5.8.2.422

### LINKED ISSUE #2677: Walk-on particles
(Using the latest version) walking on machines renders missing-texture particles:
image

### LINKED ISSUE #2690: [1.12.2][5.8.2.422] Bio Generator explode IC2 machines
Bio generator works fine when going without stopping but when stopped It can store up to 30k eu and then It will explode basically any IC2 machine. I tried looking into config files but didn't find anything related to eu output. I have a short video for demonstration.
Used IC22: IC2Classic 1.12-1.5.5.2.1
Modpack: Tekkit 2

Youtube: https://www.youtube.com/watch?v=hP7Z7bJxj5E

Thanks.

### LINKED ISSUE #2704: "Very Large" farm layout in Forester's Manual is wrong
The center area (in black) shows 3x5 (rather than 5x5):
image

### LINKED ISSUE #2709: Cocoa Plantation farm does not auto-plant harvested cocoa beans
Unlike other farm types that don't get rid of the "seed", cocoa plantations will simply run out of cocoa beans.

### LINKED ISSUE #2724: Allow Butterflies to live indefinitely
Currently trying to keep butterflies inside of an enclosed modded building causes them over time to all die as they randomly take suffocation damage.

### PR DESCRIPTION
**Pull request by ACGaming**
This PR merges several established fixes from Universal Tweaks along with some extras.

- Fix backpack duplication glitch, references Focamacho/DupeFix-Project#47
- Fix letter comparison, closes #2574
- Fix carpenter duplication glitch, closes #2579
- Enable cocoa replanting, closes #2709
- Add hive damage ignore armor config (requested by Tekkit 2 players)
- Limit offered energy for Bio Generator, closes #2690
- Fix 'Very Large' farm layout in almanac, closes #2704
- Add landing and running effects for blocks, closes #1200, closes #2677
- Add butterfly maximum lifespan config, closes #2724

### CODE REVIEW

File: src/main/java/forestry/core/inventory/ItemInventory.java [hunk 1]
```diff
@@ -133,6 +134,10 @@ private static boolean isSameItemInventory(ItemStack base, ItemStack comparison)
 			return false;
 		}
 
+		if (comparison.getItem() instanceof ItemLetter) {
+			return false;
```
Comment (thedarkcolour) [inline src/main/java/forestry/core/inventory/ItemInventory.java]: I don't think ignoring this check for letters is the correct fix. The correct solution would likely be to change the `String uid` field in Letter.java to be an `int` instead.

File: src/main/java/forestry/lepidopterology/entities/EntityButterfly.java [hunk 2]
```diff
@@ -78,7 +78,7 @@ public class EntityButterfly extends EntityCreature implements IEntityButterfly
 
 	public static final int EXHAUSTION_REST = 1000;
 	public static final int EXHAUSTION_CONSUMPTION = 100 * EXHAUSTION_REST;
-	public static final int MAX_LIFESPAN = 24000 * 7; // one minecraft week in ticks
+	public static final int MAX_LIFESPAN = ModuleLepidopterology.maxLifespan;
```
Comment (thedarkcolour) [inline src/main/java/forestry/lepidopterology/entities/EntityButterfly.java]: Please use `ModuleLepidopterology.maxLifespan` directly instead of making a constant. While using a constant might not affect anything now, it will cause headaches down the line if Forestry configs become reloadable.

File: src/main/resources/assets/forestry/lang/en_us.lang [hunk 3]
```diff
@@ -1836,6 +1838,8 @@ for.config.butterfly.entities.maximum=Butterfly Maximum
 for.config.butterfly.entities.maximum.comment=New butterflies will stay in item form and will not take flight once this limit is reached.
 for.config.butterfly.entities.maxDistance=Maximum Distance To Home
 for.config.butterfly.entities.maxDistance.comment=Butterflies will fly home if they are too far away from it.
+for.config.butterfly.entities.maxLifespan=Maximum Lifespan
+for.config.butterfly.entities.maxLifespan.comment=Butterflies will die if their specified lifespan in ticks is exceeded.
```
Comment (thedarkcolour) [inline src/main/resources/assets/forestry/lang/en_us.lang]: Mention that setting maximum lifespan to 0 will prevent butterflies from dying altogether.

File: src/main/resources/assets/forestry/lang/en_us.lang [hunk 4]
```diff
@@ -1819,6 +1819,8 @@ for.config.beekeeping.hivedamage.onlyAfterAttack=Defend Hive Damage
 for.config.beekeeping.hivedamage.onlyAfterAttack.comment=The bees only attack the player if he starts to destroy the hive.
 for.config.beekeeping.hivedamage.onlyPlayers=Player Hive Damage
 for.config.beekeeping.hivedamage.onlyPlayers.comment=Whether bees can damage other entities than the player.
+for.config.beekeeping.hivedamage.ignoreArmor=Hive Damage Ignores Armor
```
Comment (thedarkcolour) [inline src/main/resources/assets/forestry/lang/en_us.lang]: "Pierces armor" might be clearer wording, but up to you.

**Review by thedarkcolour — CHANGES_REQUESTED** [review]

File: src/main/java/forestry/core/inventory/ItemInventory.java
Comment (thedarkcolour) [inline src/main/java/forestry/core/inventory/ItemInventory.java:1]: Remove this stray import

**Review by thedarkcolour — CHANGES_REQUESTED** [review]

**Review by thedarkcolour — APPROVED** [review]
